# Generated by Django 5.1.4 on 2025-10-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_project_image_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='allow_downloads',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='license',
            field=models.CharField(choices=[('All Rights Reserved', 'All Rights Reserved'), ('Creative Commons', 'Creative Commons'), ('MIT', 'MIT')], default='All Rights Reserved', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=20),
        ),
    ]
