# Generated by Django 5.2.7 on 2025-10-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_message_recipient_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='appreciation_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
