# Generated by Django 5.2.7 on 2025-10-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
